### PR TITLE
v0.73.1

### PR DESCRIPTION
**Pull request by orso82**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by orso82** [comment]
@conda-forge-admin, please rerender

**Comment by smithsp** [comment]
@conda-forge-admin, please rerender

**Comment by smithsp** [comment]
@conda-forge-admin, please rerender

**Comment by smithsp** [comment]
@orso82 Are you OK if we merge this as is?  I had to disable the windows build, but mac and linux are OK with cython.

**Comment by smithsp** [comment]
@orso82 You never acted on this one, which allows for the cython optimizations.

**Comment by smithsp** [comment]
Not sure how this stayed open.  I am going to close it.

**Pull request closed without merging**
